/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.overbond;

import com.overbond.entities.*;
import com.overbond.services.CalculateService;
import com.overbond.services.OutputService;
import com.overbond.services.InputService;
import org.apache.commons.lang3.StringUtils;

import java.io.IOException;
import java.util.List;

/*
    Since this is a command line utility, we will be sticking to standard out.
    However, the loggers are wired in for future extensions.
 */
public class App {


    public static void main(String[] args) {


        if(args.length <= 1){
            System.out.println("Empty arguments");
            return;
        }

        try{
            GenericBond[] genericBonds = InputService.readDataFromSource(args[0]);
            List<Spread> spreads = CalculateService.calculateSpread(genericBonds);
            OutputService.printOutputToSpecifiedPath(spreads, args[1]);
        } catch (IOException e) {
            System.out.println("Error reading/writing to file " + e);
        }

    }

}
