/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.overbond;

import com.overbond.entities.*;
import com.overbond.services.CalculateService;
import com.overbond.services.OutputService;
import com.overbond.services.InputService;
import org.apache.commons.lang3.StringUtils;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.io.IOException;
import java.util.List;

/*
    Entry point of the program
 */
public class App {
    private static Logger logger = LoggerFactory.getLogger(App.class);

    public static void main(String[] args) {

        // Don't execute if there is less argument
        if(args.length <= 1){
            logger.info("Empty arguments");
            return;
        }

        try{
            GenericBond[] genericBonds = InputService.readDataFromSource(args[0]);
            List<Spread> spreads = CalculateService.calculateSpread(genericBonds);
            OutputService.printOutputToSpecifiedPath(spreads, args[1]);
        } catch (IOException e) {
            logger.error("Error reading/writing to file ", e);
        }

    }

}
