/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.overbond;

import com.overbond.entities.*;
import com.overbond.services.CalculateService;
import com.overbond.services.OutputService;
import com.overbond.services.ReadInputService;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.io.IOException;
import java.util.List;

/*
    Since this is a command line utility, we will be sticking to standard out.
    However, the loggers are wired in for future extensions.
 */
public class App {

    private static List<GovernmentBond> governmentBonds;
    private static List<CorporateBond> corporateBonds;

    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {

        try{
            GenericBond[] genericBonds = ReadInputService.readDataFromSource(args[0]);
            List<Spread> spreads = CalculateService.calculateSpread(genericBonds);
            OutputService.printOutputToSpecifiedPath(spreads, args[1]);
        } catch (IOException e) {
            System.out.println("Error reading/writingto file" + e);
        }

    }

}
